/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pbo2.app;

import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class KonversiSuhuView extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public KonversiSuhuView() {
        initComponents();
        this.setEnableRadioButtons(false, true, true, true, 1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        satuanSuhuGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jRadioButtonCelcius = new javax.swing.JRadioButton();
        jRadioButtonFahrenheit = new javax.swing.JRadioButton();
        jRadioButtonReamur = new javax.swing.JRadioButton();
        jRadioButtonKelvin = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("APLIKASI KONVERSI SUHU");

        jLabel2.setText("Input Suhu");

        jLabel3.setText("Pilih Jenis Konversi");

        jLabel4.setText("Tujuan Koversi");

        jLabel5.setText("Hasil Konversi");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Celcius", "Fahrenheit", "Reamur", "Kelvin" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButton1.setText("Konversi");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        satuanSuhuGroup.add(jRadioButtonCelcius);
        jRadioButtonCelcius.setText("Celcius");
        jRadioButtonCelcius.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButtonCelciusItemStateChanged(evt);
            }
        });

        satuanSuhuGroup.add(jRadioButtonFahrenheit);
        jRadioButtonFahrenheit.setSelected(true);
        jRadioButtonFahrenheit.setText("Fahrenheit");
        jRadioButtonFahrenheit.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButtonFahrenheitItemStateChanged(evt);
            }
        });

        satuanSuhuGroup.add(jRadioButtonReamur);
        jRadioButtonReamur.setText("Reamur");
        jRadioButtonReamur.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jRadioButtonReamurStateChanged(evt);
            }
        });

        satuanSuhuGroup.add(jRadioButtonKelvin);
        jRadioButtonKelvin.setText("Kelvin");
        jRadioButtonKelvin.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButtonKelvinItemStateChanged(evt);
            }
        });

        jScrollPane1.setViewportView(jTextPane1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField1)
                    .addComponent(jButton1)
                    .addComponent(jComboBox1, 0, 289, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jRadioButtonCelcius)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonFahrenheit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonReamur)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButtonKelvin))
                    .addComponent(jScrollPane1))
                .addContainerGap(169, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(196, 196, 196))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jRadioButtonCelcius)
                    .addComponent(jRadioButtonFahrenheit)
                    .addComponent(jRadioButtonReamur)
                    .addComponent(jRadioButtonKelvin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(119, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        if (!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextField1KeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(jTextField1.getText().isBlank()){
            JOptionPane.showMessageDialog(null, "Input Suhu Tidak Boleh Kosong", "Awas", JOptionPane.WARNING_MESSAGE);
            jTextField1.requestFocus();
            return;
        }
        
        this.operasiKonversi();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        this.operasiKonversi();
    }//GEN-LAST:event_jTextField1KeyReleased

    private void jRadioButtonCelciusItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButtonCelciusItemStateChanged
        this.operasiKonversi();
    }//GEN-LAST:event_jRadioButtonCelciusItemStateChanged

    private void jRadioButtonReamurStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jRadioButtonReamurStateChanged
        this.operasiKonversi();
    }//GEN-LAST:event_jRadioButtonReamurStateChanged

    private void jRadioButtonKelvinItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButtonKelvinItemStateChanged
        this.operasiKonversi();
    }//GEN-LAST:event_jRadioButtonKelvinItemStateChanged

    private void jRadioButtonFahrenheitItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButtonFahrenheitItemStateChanged
        this.operasiKonversi();
    }//GEN-LAST:event_jRadioButtonFahrenheitItemStateChanged

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        String itemSelected = jComboBox1.getSelectedItem().toString();
        if (itemSelected.equalsIgnoreCase("Celcius")) {
            this.setEnableRadioButtons(false, true, true, true, 1);
        } else if (itemSelected.equalsIgnoreCase("Fahrenheit")) {
            this.setEnableRadioButtons(true, false, true, true, 0);
        } else if (itemSelected.equalsIgnoreCase("Reamur")) {
            this.setEnableRadioButtons(true, true, false, true, 0);
        } else if (itemSelected.equalsIgnoreCase("Kelvin")) {
            this.setEnableRadioButtons(true, true, true, false, 0);
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void setEnableRadioButtons(
            boolean celcius,
            boolean fahrenheit,
            boolean reamur,
            boolean kelvin,
            int selectRadioButton
    ) {
        jRadioButtonCelcius.setEnabled(celcius);
        jRadioButtonFahrenheit.setEnabled(fahrenheit);
        jRadioButtonReamur.setEnabled(reamur);
        jRadioButtonKelvin.setEnabled(kelvin);

        switch (selectRadioButton) {
            case 0 ->
                jRadioButtonCelcius.setSelected(true);
            case 1 ->
                jRadioButtonFahrenheit.setSelected(true);
            case 2 ->
                jRadioButtonReamur.setSelected(true);
            case 3 ->
                jRadioButtonKelvin.setSelected(true);
            default ->
                JOptionPane.showMessageDialog(null, "Tidak ada Radio Button YG sesuai", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    public void operasiKonversi() {
        if (jTextField1.getText().isBlank()) {
            return;
        }

        String suhuSelected = jComboBox1.getSelectedItem().toString();
        double suhu = Double.parseDouble(jTextField1.getText());
        if (suhuSelected.equalsIgnoreCase("Celcius") && this.jRadioButtonFahrenheit.isSelected()) {
            this.tampilkanOutput(
                    this.celsiusToFahrenheit(suhu),
                    "°F"
            );
        } else if (suhuSelected.equalsIgnoreCase("Celcius") && this.jRadioButtonReamur.isSelected()) {
            this.tampilkanOutput(
                    this.celsiusToReamur(suhu),
                    "°R"
            );
        } else if (suhuSelected.equalsIgnoreCase("Celcius") && this.jRadioButtonKelvin.isSelected()) {
            this.tampilkanOutput(
                    this.celsiusToKelvin(suhu),
                    "°K"
            );
        } else if (suhuSelected.equalsIgnoreCase("Fahrenheit") && this.jRadioButtonCelcius.isSelected()) {
            this.tampilkanOutput(
                    this.fahrenheitToCelsius(suhu),
                    "°C"
            );
        } else if (suhuSelected.equalsIgnoreCase("Fahrenheit") && this.jRadioButtonReamur.isSelected()) {
            this.tampilkanOutput(
                    this.fahrenheitToReamur(suhu),
                    "°R"
            );
        } else if (suhuSelected.equalsIgnoreCase("Fahrenheit") && this.jRadioButtonKelvin.isSelected()) {
            this.tampilkanOutput(
                    this.fahrenheitToKelvin(suhu),
                    "°K"
            );
        } else if (suhuSelected.equalsIgnoreCase("Reamur") && this.jRadioButtonCelcius.isSelected()) {
            this.tampilkanOutput(
                    this.reamurToCelsius(suhu),
                    "°C"
            );
        } else if (suhuSelected.equalsIgnoreCase("Reamur") && this.jRadioButtonFahrenheit.isSelected()) {
            this.tampilkanOutput(
                    this.reamurToFahrenheit(suhu),
                    "°F"
            );
        } else if (suhuSelected.equalsIgnoreCase("Reamur") && this.jRadioButtonKelvin.isSelected()) {
            this.tampilkanOutput(
                    this.reamurToKelvin(suhu),
                    "°K"
            );
        } else if (suhuSelected.equalsIgnoreCase("Kelvin") && this.jRadioButtonCelcius.isSelected()) {
            this.tampilkanOutput(
                    this.kelvinToCelsius(suhu),
                    "°C"
            );
        } else if (suhuSelected.equalsIgnoreCase("Kelvin") && this.jRadioButtonFahrenheit.isSelected()) {
            this.tampilkanOutput(
                    this.kelvinToFahrenheit(suhu),
                    "°F"
            );
        } else if (suhuSelected.equalsIgnoreCase("Kelvin") && this.jRadioButtonReamur.isSelected()) {
            this.tampilkanOutput(
                    this.kelvinToReamur(suhu),
                    "°R"
            );
        }
    }

    public void tampilkanOutput(double value, String satuan) {
        this.jTextPane1.setText(String.format("%.2f %s", value, satuan));
    }

    public double celsiusToFahrenheit(double celsius) {
        return (celsius * 9 / 5) + 32;
    }

    public double celsiusToReamur(double celsius) {
        return celsius * 4 / 5;
    }

    public double celsiusToKelvin(double celsius) {
        return celsius + 273.15;
    }

    public double fahrenheitToCelsius(double fahrenheit) {
        return (fahrenheit - 32) * 5 / 9;
    }

    public double fahrenheitToReamur(double fahrenheit) {
        return (fahrenheit - 32) * 4 / 9;
    }

    public double fahrenheitToKelvin(double fahrenheit) {
        return (fahrenheit - 32) * 5 / 9 + 273.15;
    }

    public double reamurToCelsius(double reamur) {
        return reamur * 5 / 4;
    }

    public double reamurToFahrenheit(double reamur) {
        return (reamur * 9 / 4) + 32;
    }

    public double reamurToKelvin(double reamur) {
        return (reamur * 5 / 4) + 273.15;
    }

    public double kelvinToCelsius(double kelvin) {
        return kelvin - 273.15;
    }

    public double kelvinToFahrenheit(double kelvin) {
        return (kelvin - 273.15) * 9 / 5 + 32;
    }

    public double kelvinToReamur(double kelvin) {
        return (kelvin - 273.15) * 4 / 5;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KonversiSuhuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KonversiSuhuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KonversiSuhuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KonversiSuhuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KonversiSuhuView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButtonCelcius;
    private javax.swing.JRadioButton jRadioButtonFahrenheit;
    private javax.swing.JRadioButton jRadioButtonKelvin;
    private javax.swing.JRadioButton jRadioButtonReamur;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.ButtonGroup satuanSuhuGroup;
    // End of variables declaration//GEN-END:variables
}
